### ISSUE TITLE
Identation for multi-level lists

### ISSUE THREAD

**Issue by sabrinang** [mozilla/web-lit-core#11]
@zee-moz and @anmechung are using the template and notice that their multi-level lists are not indenting: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/36876391-a35b8484-1d69-11e8-98de-52e552acb7c4.png">

@gvn I believe this indentation issue was addressed in https://github.com/mozilla/web-lit-core/pull/2#issuecomment-365067030 but maybe it has not applied to the main text.

**Comment by zee-moz** [comment]
@sabrinang  I would also prefer if the first level bullets would indent a bit, too, to set the lists off from the rest of the text-- more like in a traditional word document. I think when they're justified with the main text they lose some of their flair. Is that possible? Or is that part of the design?

**Comment by gvn** [comment]
@sabrinang How many pixels of indentation should I add?

**Comment by sabrinang** [comment]
@gvn Can we use bootstrap default indentation to unify? https://getbootstrap.com/docs/4.0/content/reboot/#lists I'm not quite sure specifically how many pixels it uses though.
