### ISSUE TITLE
Looking for glossary of web terms

### ISSUE THREAD

**Issue by anmechung** [mozilla/web-lit-core#12]
Rather than reinvent the wheel, can anyone recommend a good glossary of basic web terms?  We're looking to add it to the Map the Web activity.

**Comment by RandyIA** [comment]
I've started working on this; [Map the Web - Glossary of Terms](https://docs.google.com/spreadsheets/d/19TK6dtIbXoQjvc_Zp7vDkItDjW2NBs-RzYr8RzGv2EE/edit?usp=sharing). You and anyone else are welcome to contribute and use. :-)
