### ISSUE TITLE
Add functional "suggest changes" button

### ISSUE THREAD

**Issue by zee-moz** [mozilla/web-lit-core#13]
On the original template we had a "suggest changes button" but it was giving a 404 error rather than taking users to edit the file.  Someone (@anmechung) removed the links which is good for now, but it would be great to have that feature back. @gvn hoping you can make this tweak.

**Comment by anmechung** [comment]
@zee-moz I did remove the code for the link as there is also one at the bottom of the page as well.  I can add it back in at the top as well, but do we need it in two places?  FYI - the link at the bottom of the page also gives a 404 error.  Perhaps @gvn can make the tweak here?

**Comment by zee-moz** [comment]
I suppose it's possible that people will be more likely to see it and click if it's in two places. 
I'm also wondering if it's better if it takes people directly to an issue about the lesson where they can comment, rather than to the editor for the page (which is what it was supposed to do). As most of our audience won't know GH well enough to know what's happening if they come to that editing screen, the issue might be more user friendly. Not sure that the link to an issue can be created dynamically in the template though.
