### ISSUE TITLE
In the README, we should say why Web Literacy is so important.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/web-lit-core#20]
What do we mean when we say this?

> Thus, please spread the word on why it's important for people in their everyday lives to have these core skills...

Are there 3-5 bullet points we can list or snippets Web Lit Leaders can provide as reasons/testimonials (e.g., "My patrons need to develop web literacy to have access to educational resources we don;' have in our community.")? 

Alternatively, might we use our current Internet health 1-liner?

**Comment by anmechung** [comment]
Good idea - can you send me examples of 3 bullet points and I'll add?

**Comment by chadsansing** [comment]
Maybe something like this?

> Web literacy helps people:
> 
> -Understand how the Internet works and connects different parts of the web.
> -Share information with others in ways that make sense and protect their privacy and security.
> -Empower themselves and their communities to participate online as citizens, learners, workers, creators, consumers, and people.

**Comment by anmechung** [comment]
Great!  Added.
