### ISSUE TITLE
Sort navigation links alphabetically

### ISSUE THREAD

**Issue by alanmoo** [mozilla/web-lit-core#22]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/1682681/38097836-6e5d5762-3344-11e8-9698-1df8a6eb93f6.png">

These links on the overview page should be alphabetically sorted so the links at the bottom of the individual lessons link to the next item in the nav. (The first `Overview` and last link (added in #21) stay where they are)

(Follow up based on [this comment](https://github.com/mozilla/web-lit-core/issues/10#issuecomment-377120013), which I believe addresses the issue. Is that correct, @anmechung?)

**Comment by anmechung** [comment]
@alanmoo I may not be understanding correctly, but It's not alphabetical.  The lessons build on the one before and the one after in terms of sequence.

**Comment by alanmoo** [comment]
I closed this because it's not the right work that needs to be done. We should open up another ticket that properly captures it.

**Comment by anmechung** [comment]
Got it!  Thx - I just sent you something via slack too to try and make this a bit easier.  I know how busy you guys are right now.
