### ISSUE TITLE
Fix previous/next buttons at bottom of each activity page

### ISSUE THREAD

**Issue by anmechung** [mozilla/web-lit-core#23]
@alanmoo @gvn - the buttons at the bottom of each activity page look great, but they are linked to the wrong activities. Previous and next should be in this sequential order: 
Overview
Web and You
Map The Web
Make Friends With Your Browser
Search Party
Web Detective
Design On The Web
Tagging 101
Building Basic Pages
Web Apps And Build With Thimble
Web Builders
Safety First
All The Stickerz
Crowdsourcing On The Web

cc: @zee-moz

**Comment by alanmoo** [comment]
#21 will remove the previous/next links from the footer of each page. "Next" buttons can be added by including a new line at the top of each page

`following: _articles/{filename of next page}.md`

**Comment by anmechung** [comment]
Done- thanks!
